language: python
python:
  - "3.6"
script:
  - python -m unittest
deploy:
  provider: heroku
  api_key:
    secure: Tq2RNTV/HxFYFuPFsJZkBPoCVqZGH8Wlab0gUeFLCm0WCRAEIP8fTsJsWYECf6VGWaQ4uqpmmVGALOowI5rqI9/nWTA93PVxcqqmVIYK/i3CsKpISSWU1fibWsiffBQZ/UBzNYJRaDP+oRlNYXB8avU1Sl3pmmEGDKM6Itqy35xNOW5uLkoU/ov/tZgpJngB57BL45xmEH49CrI97orpHpfPAoiHYf0fAYE2wAEgRqNpaEl6MTDU71lsUhHCUg7jTr2+XUFlVjfoqdegzmCX8UxEnLLdTVOmDTgrDmSGfos4D4WiPUM/QgDTXvjC5/y5PRG6BRNy/IoyXJSHu1i0FJMohVTm7zKEI4/TpKiTbb/dBV30PaZgXY1YSm4SsIZlsBN2FPVBpkSUAZOAyG8ttjY8Tla6hj+oMiixnzBsecavssfX3Umq/k6PV8aGiJgUDk/Gbln06AbPPbMChIh+f0q14DisylHpjIVsbQem6srb/SisPM4PzFF0brD6xiYd5EQRYJe1Zn2tzDf0qe8SA0t2kxrLCqJ2ARoJuneCuhCd6I58k/NnU8ZhUjWH4w9y4/INX13qP71i+BgISHD6mtdh5gJ8UgWRvlteP5EBqTyTx3MbwIKWXzdkx5ZHtNJ+Veuj07AJZC+g096820mKepiW4ywfINCmc609BgLsBGg=
  app: customer-map
  on:
    repo: chrisly-bear/PythonClass2019
