language: python
python:
  - "3.6"
script:
  - python -m unittest
deploy:
  provider: heroku
  api_key:
    secure: avINvU2Elthjn2oBh2jJmwaJpRz0ngW/WNCbEDIKx7Wv9gog+POGVmFqgtHXZEKwxVKPx1dAZwg0HFd1j+ctEqup26X5EhnQH9/FsQJ3i4e7PBVCn9/GI99LFxvsegmjejoSL18kMupsujfNhXEck+7qSDZfs6H/poqe0r8zKJMyMWycefoNG5qwOuCD+zYk4fprwpp4VCyjrxyxU3a7J1Jw7yc6kxGDG0XY9XXqqOzfh6fTWCEOYDphJxINj0kwOavHfQFisKm66AJGmVzPt/wyoO5Gcro3PAFsr5EBB8941pmgPScHVGjPu6MEDNYxRzXxJ2WNe3mTKLIHwJSf2aakYvtdIUCyh/ESXkOXPSemDx20qexSyEhlj6owio2Ojg/sQvjKfrXnXwlE718Rz/r26O8s61Y9X7OXJKxsbj5+NSMVFTDXUONPpbWQ38VmCip97OZH0igVeiaRmj1hgQz4GlOGANvZAompoBI6nEkedIQy83lDr22IBXZOx3wo+jlhBCqL47Yv+gLKyWnbBVUzQ7bu30BiOtX2kpDTxX3MDQTOT7v8vyzdXlTdShWhV9Hhi7G3H/wx1SzdOPvsO9qjC7pJ2QQO70CfPD7x2YYO9O+t0GX8nxcqa/Dzt8Hl39XezQQLPEpw+YgGZT+gobQ5PDPUW2JS6Hss0AnTchw=
  app: customer-map
  on:
    repo: chrisly-bear/PythonClass2019
